//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public College()
        {
            this.Department = new HashSet<Department>();
            this.CollegeEmployee = new HashSet<CollegeEmployee>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CollegeNum { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> EmployeeID2 { get; set; }
        public int ProgramID { get; set; }
        public Nullable<decimal> AcceptanceRate1 { get; set; }
        public Nullable<decimal> AcceptanceRate2 { get; set; }
        public Nullable<decimal> AcceptanceRate3 { get; set; }
        public Nullable<decimal> AcceptanceRate4 { get; set; }
        public Nullable<decimal> AcceptanceRate5 { get; set; }
        public Nullable<int> CollegeFID { get; set; }
        public bool IsLast { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeEmployee> CollegeEmployee { get; set; }
    }
}
