//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseOptionalCourses = new HashSet<CourseOptionalCourses>();
            this.OfferdCourse = new HashSet<OfferdCourse>();
            this.PlanCourse = new HashSet<PlanCourse>();
            this.PreRequest = new HashSet<PreRequest>();
            this.StdSection = new HashSet<StdSection>();
            this.StdSection1 = new HashSet<StdSection>();
        }
    
        public int ID { get; set; }
        public string OldCourseCode { get; set; }
        public string OldCourseCode2 { get; set; }
        public string CourseCode { get; set; }
        public string CourseCode1 { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> CourseFID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public int CourseCategoryID { get; set; }
        public int CCourseTypeID { get; set; }
        public Nullable<int> CourseType { get; set; }
        public int NumOfHours { get; set; }
        public int RequestedFHours { get; set; }
        public bool IsScholarship { get; set; }
        public bool IsHaveLab { get; set; }
        public bool IsHaveDiscussion { get; set; }
        public bool IsLast { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<int> DepartmentID1 { get; set; }
    
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual CourseType CourseType1 { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseOptionalCourses> CourseOptionalCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferdCourse> OfferdCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCourse> PlanCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest> PreRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSection> StdSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSection> StdSection1 { get; set; }
    }
}
