//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Plan = new HashSet<Plan>();
            this.SectionDepartment = new HashSet<SectionDepartment>();
            this.StudentAcademic = new HashSet<StudentAcademic>();
            this.Course = new HashSet<Course>();
        }
    
        public int ID { get; set; }
        public int CollegeID { get; set; }
        public int DepartmentNum { get; set; }
        public string DepartmentCode { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<decimal> AcceptanceRate1 { get; set; }
        public Nullable<decimal> AcceptanceRate2 { get; set; }
        public Nullable<decimal> AcceptanceRate3 { get; set; }
        public Nullable<decimal> AcceptanceRate4 { get; set; }
        public Nullable<decimal> AcceptanceRate5 { get; set; }
        public int MaxStudyLevelID { get; set; }
        public int HourCost { get; set; }
        public int StdMCapacity { get; set; }
        public int StdFMCapacity { get; set; }
        public int UniversityHour { get; set; }
        public int CollegeHour { get; set; }
        public int DepartmentHour { get; set; }
        public int OptionalHour { get; set; }
        public int MarkOfSuccess { get; set; }
        public Nullable<int> DepartmentFID { get; set; }
        public bool IsLast { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        public virtual College College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionDepartment> SectionDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAcademic> StudentAcademic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
    }
}
