//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IsraaAcademicEntities : DbContext
    {
        public IsraaAcademicEntities()
            : base("name=IsraaAcademicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FinalExamSection> FinalExamSection { get; set; }
        public virtual DbSet<OfferdCourse> OfferdCourse { get; set; }
        public virtual DbSet<OfferdCourseType> OfferdCourseType { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<StdSection> StdSection { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Lecture> Lecture { get; set; }
        public virtual DbSet<EmplyeeView> EmplyeeView { get; set; }
        public virtual DbSet<StudentsView> StudentsView { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<College> College { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<PlanCourse> PlanCourse { get; set; }
        public virtual DbSet<ProgramLevel> ProgramLevel { get; set; }
        public virtual DbSet<SemesterStatus> SemesterStatus { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<StudentAcademicLog> StudentAcademicLog { get; set; }
        public virtual DbSet<StdStatus> StdStatus { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<SectionDepartment> SectionDepartment { get; set; }
        public virtual DbSet<StudyLevel> StudyLevel { get; set; }
        public virtual DbSet<StudentAcademic> StudentAcademic { get; set; }
        public virtual DbSet<StudentStatus> StudentStatus { get; set; }
        public virtual DbSet<StudentTypes> StudentTypes { get; set; }
        public virtual DbSet<WarningStatus> WarningStatus { get; set; }
        public virtual DbSet<StdAcademicWarning> StdAcademicWarning { get; set; }
        public virtual DbSet<WarningType> WarningType { get; set; }
        public virtual DbSet<GraduationStatus> GraduationStatus { get; set; }
        public virtual DbSet<StudentSuspended> StudentSuspended { get; set; }
        public virtual DbSet<MidtermExamSection> MidtermExamSection { get; set; }
        public virtual DbSet<PreRequest> PreRequest { get; set; }
        public virtual DbSet<StdSemester> StdSemester { get; set; }
        public virtual DbSet<CourseOptionalCourses> CourseOptionalCourses { get; set; }
        public virtual DbSet<MarkTitle> MarkTitle { get; set; }
        public virtual DbSet<CourseCategory> CourseCategory { get; set; }
        public virtual DbSet<CourseType> CourseType { get; set; }
        public virtual DbSet<StudentVolunteer> StudentVolunteer { get; set; }
        public virtual DbSet<VolunteerCategory> VolunteerCategory { get; set; }
        public virtual DbSet<VolunteerType> VolunteerType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Governorates> Governorates { get; set; }
        public virtual DbSet<CollegeEmployee> CollegeEmployee { get; set; }
        public virtual DbSet<StudentPersonal> StudentPersonal { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<ExamSectionDistribution> ExamSectionDistribution { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Course> Course { get; set; }
    
        public virtual int CalculateGPA(Nullable<int> studentID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalculateGPA", studentIDParameter);
        }
    }
}
