//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int ID { get; set; }
        public int SectionID { get; set; }
        public int RoomID { get; set; }
        public int CDayID { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan ToHour { get; set; }
        public bool IsPined { get; set; }
        public Nullable<System.DateTime> PinDate { get; set; }
        public Nullable<int> PinEmployeeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Room Room { get; set; }
    }
}
