//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public int StdSectionID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public int WorkMark { get; set; }
        public Nullable<int> OldMidtermMark { get; set; }
        public int MidtermMark { get; set; }
        public int FinalMark { get; set; }
        public int MidtermMinusMark { get; set; }
        public int FinalMinusMark { get; set; }
        public int MinusMark { get; set; }
        public int TotalMark { get; set; }
        public bool IsMidtermNoMark { get; set; }
        public Nullable<bool> IsMidtermNoMarkAccept { get; set; }
        public bool IsMidtermIncomplete { get; set; }
        public bool IsMidtermZero { get; set; }
        public bool IsFinalNoMark { get; set; }
        public Nullable<bool> IsFinalNoMarkAccept { get; set; }
        public bool IsFinalIncomplete { get; set; }
        public bool IsFinalZero { get; set; }
        public bool IsTotalZero { get; set; }
        public Nullable<System.DateTime> WorkMarkInsertDate { get; set; }
        public Nullable<int> WorkMarkEmployeeID { get; set; }
        public Nullable<System.DateTime> MidtermMarkInsertDate { get; set; }
        public Nullable<int> MidtermMarkEmployeeID { get; set; }
        public Nullable<System.DateTime> FinalMarkInsertDate { get; set; }
        public Nullable<int> FinalMarkEmployeeID { get; set; }
        public Nullable<System.DateTime> ZeroFinalMarkInsertDate { get; set; }
        public Nullable<int> ZeroFinalMarkEmployeeID { get; set; }
        public bool MidTeacherAccreditation { get; set; }
        public bool MidHeadAccreditation { get; set; }
        public bool MidDeanAccreditation { get; set; }
        public bool MidAcademicAccreditation { get; set; }
        public bool TeacherAccreditation { get; set; }
        public bool HeadAccreditation { get; set; }
        public bool DeanAccreditation { get; set; }
        public bool AcademicAccreditation { get; set; }
        public Nullable<System.DateTime> TeacherAccreditationDate { get; set; }
        public Nullable<int> TeacherAccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> HeadAccreditationDate { get; set; }
        public Nullable<int> HeadAccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> DeanAccreditationDate { get; set; }
        public Nullable<int> DeanAccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> AcademicAccreditationDate { get; set; }
        public Nullable<int> AcademicAccreditationEmployeeID { get; set; }
        public bool Revision { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<bool> MidtermRevision { get; set; }
        public Nullable<System.DateTime> MidtermRevisionDate { get; set; }
        public bool HasEdit { get; set; }
        public bool IsDelete { get; set; }
        public string MyMark { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteStudentID { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<bool> IsMidtermAccreditation { get; set; }
        public bool IsFinalAccreditation { get; set; }
        public string Note { get; set; }
    
        public virtual StdSection StdSection { get; set; }
    }
}
