//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkTitle
    {
        public int ID { get; set; }
        public Nullable<int> CourseCategoryID { get; set; }
        public int CourseTypeID { get; set; }
        public int CourseID { get; set; }
        public int SemesterID { get; set; }
        public int OfferdCourseTypeID { get; set; }
        public Nullable<int> SemesterTypeID { get; set; }
        public int OfferdCourseID { get; set; }
        public int SectionID { get; set; }
        public string Title1 { get; set; }
        public double Mark1 { get; set; }
        public string Title2 { get; set; }
        public double Mark2 { get; set; }
        public string Title3 { get; set; }
        public double Mark3 { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
