//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferdCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferdCourse()
        {
            this.SectionDepartment = new HashSet<SectionDepartment>();
            this.Section = new HashSet<Section>();
        }
    
        public int ID { get; set; }
        public int SemesterID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public int OfferdCourseTypeID { get; set; }
        public int MSectionCount { get; set; }
        public int FSectionCount { get; set; }
        public int MFSectionCount { get; set; }
        public Nullable<bool> IsEBook { get; set; }
        public Nullable<bool> IsMidtermExam { get; set; }
        public Nullable<bool> IsMidtermEExam { get; set; }
        public Nullable<System.DateTime> MidtermExamDate { get; set; }
        public Nullable<System.TimeSpan> MidtermExamTimeFrom1 { get; set; }
        public Nullable<System.TimeSpan> MidtermExamTimeTo1 { get; set; }
        public Nullable<System.TimeSpan> MidtermExamTimeFrom2 { get; set; }
        public Nullable<System.TimeSpan> MidtermExamTimeTo2 { get; set; }
        public bool IsFinalExam { get; set; }
        public Nullable<bool> IsFinalEExam { get; set; }
        public Nullable<System.DateTime> FinalExamDate { get; set; }
        public Nullable<System.TimeSpan> FinalExamTimeFrom1 { get; set; }
        public Nullable<System.TimeSpan> FinalExamTimeTo1 { get; set; }
        public Nullable<System.TimeSpan> FinalExamTimeFrom2 { get; set; }
        public Nullable<System.TimeSpan> FinalExamTimeTo2 { get; set; }
        public bool HeadAccreditation { get; set; }
        public Nullable<System.DateTime> HeadAccreditationDate { get; set; }
        public Nullable<int> HeadAccreditationEmployeeID { get; set; }
        public bool DeanAccreditation { get; set; }
        public Nullable<System.DateTime> DeanAccreditationDate { get; set; }
        public Nullable<int> DeanAccreditationEmployeeID { get; set; }
        public bool AcademicAccreditation { get; set; }
        public Nullable<System.DateTime> AcademicAccreditationDate { get; set; }
        public Nullable<int> AcademicAccreditationEmployeeID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionDepartment> SectionDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Section { get; set; }
        public virtual Course Course { get; set; }
    }
}
