//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.PlanCourse = new HashSet<PlanCourse>();
            this.StudentAcademic = new HashSet<StudentAcademic>();
        }
    
        public int ID { get; set; }
        public string PlanNum { get; set; }
        public int DepartmentID { get; set; }
        public string Year { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public bool HeadAccreditation { get; set; }
        public Nullable<System.DateTime> HeadAccreditationDate { get; set; }
        public Nullable<int> HeadAccreditationEmployeeID { get; set; }
        public bool DeanAccreditation { get; set; }
        public Nullable<System.DateTime> DeanAccreditationDate { get; set; }
        public Nullable<int> DeanAccreditationEmployeeID { get; set; }
        public bool AcademicAccreditation { get; set; }
        public Nullable<System.DateTime> AcademicAccreditationDate { get; set; }
        public Nullable<int> AcademicAccreditationEmployeeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<int> NumOfHours { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCourse> PlanCourse { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAcademic> StudentAcademic { get; set; }
    }
}
