//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.College = new HashSet<College>();
            this.StudentAcademic = new HashSet<StudentAcademic>();
        }
    
        public int ID { get; set; }
        public int ProgramNum { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public int Admissionkey { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployeeID2 { get; set; }
        public Nullable<int> PassMark { get; set; }
        public Nullable<int> ZeroMark { get; set; }
        public Nullable<int> ProgramWarningHourTo { get; set; }
        public Nullable<double> ProgramWarningGPA { get; set; }
        public Nullable<double> ProgramWarningFatalGPA { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<College> College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAcademic> StudentAcademic { get; set; }
    }
}
