//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.ExamSectionDistribution = new HashSet<ExamSectionDistribution>();
            this.FinalExamSection = new HashSet<FinalExamSection>();
            this.Lecture = new HashSet<Lecture>();
            this.MidtermExamSection = new HashSet<MidtermExamSection>();
        }
    
        public int ID { get; set; }
        public int RoomNum { get; set; }
        public string Name { get; set; }
        public int BuildingID { get; set; }
        public string Floor { get; set; }
        public Nullable<double> Area { get; set; }
        public int RoomTypeID { get; set; }
        public Nullable<bool> IsLectureUsed { get; set; }
        public Nullable<int> LectureCapacity { get; set; }
        public Nullable<bool> IsExamUsed { get; set; }
        public int ExamCapacity { get; set; }
        public string UseType { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteUserID { get; set; }
        public int SeatNum { get; set; }
        public int ExamNum { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamSectionDistribution> ExamSectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalExamSection> FinalExamSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lecture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MidtermExamSection> MidtermExamSection { get; set; }
    }
}
