//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.FinalExamSection = new HashSet<FinalExamSection>();
            this.Lecture = new HashSet<Lecture>();
            this.MidtermExamSection = new HashSet<MidtermExamSection>();
            this.SectionDepartment = new HashSet<SectionDepartment>();
            this.StdSection = new HashSet<StdSection>();
            this.ExamSectionDistribution = new HashSet<ExamSectionDistribution>();
        }
    
        public int ID { get; set; }
        public int OfferdCourseID { get; set; }
        public int SectionNum { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> PTEmployeeID { get; set; }
        public int SectionType { get; set; }
        public int Gender { get; set; }
        public int Capacity { get; set; }
        public int StudentCount { get; set; }
        public bool IsActive { get; set; }
        public int MidTeacherAccreditationCount { get; set; }
        public int FinalTeacherAccreditationCount { get; set; }
        public bool IsMidTeacherAllAccreditation { get; set; }
        public bool IsFinalTeacherAllAccreditation { get; set; }
        public int MidDeanAccreditationCount { get; set; }
        public int FinalDeanAccreditationCount { get; set; }
        public bool IsMidDeanAllAccreditation { get; set; }
        public bool IsFinalDeanAllAccreditation { get; set; }
        public int MidAcademicAccreditationCount { get; set; }
        public int FinalAcademicAccreditationCount { get; set; }
        public bool IsMidAcademicAllAccreditation { get; set; }
        public bool IsFinalAcademicAllAccreditation { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalExamSection> FinalExamSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lecture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MidtermExamSection> MidtermExamSection { get; set; }
        public virtual OfferdCourse OfferdCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionDepartment> SectionDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSection> StdSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamSectionDistribution> ExamSectionDistribution { get; set; }
    }
}
