//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionDepartment
    {
        public int ID { get; set; }
        public int OfferdCourseID { get; set; }
        public int SectionID { get; set; }
        public int DepartmentID { get; set; }
        public int StudyLevelID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string BlockNum { get; set; }
        public int StudentCount { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual OfferdCourse OfferdCourse { get; set; }
        public virtual StudyLevel StudyLevel { get; set; }
        public virtual Section Section { get; set; }
    }
}
