//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester()
        {
            this.OfferdCourse = new HashSet<OfferdCourse>();
            this.StdStatus = new HashSet<StdStatus>();
            this.StdSemester = new HashSet<StdSemester>();
            this.StudentVolunteer = new HashSet<StudentVolunteer>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> SemesterTypeID { get; set; }
        public System.DateTime StudentRegisterBeginning { get; set; }
        public System.DateTime StudentRegisterEnd { get; set; }
        public System.DateTime RegisterBeginning { get; set; }
        public System.DateTime RegisterEnd { get; set; }
        public Nullable<System.DateTime> InstructorStudyBeginning { get; set; }
        public Nullable<System.DateTime> InstructorStudyEnd { get; set; }
        public System.DateTime StudyBeginning { get; set; }
        public System.DateTime StudyEnd { get; set; }
        public System.DateTime AddBeginning { get; set; }
        public System.DateTime AddEnd { get; set; }
        public System.DateTime DelayEnd { get; set; }
        public System.DateTime WithdrawEnd { get; set; }
        public System.DateTime StartMidtermExams { get; set; }
        public System.DateTime EndMidtermlExams { get; set; }
        public System.DateTime MidtermExamResults { get; set; }
        public System.DateTime MidtermExamRevisionBeginning { get; set; }
        public System.DateTime MidtermExamRevisionEnd { get; set; }
        public System.DateTime StartFinalExams { get; set; }
        public System.DateTime EndFinalExams { get; set; }
        public string MarkResults { get; set; }
        public System.DateTime MarkRevisionBeginning { get; set; }
        public System.DateTime MarkRevisionEnd { get; set; }
        public System.DateTime DeadlinePayment { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public string ArShortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferdCourse> OfferdCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdStatus> StdStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSemester> StdSemester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentVolunteer> StudentVolunteer { get; set; }
    }
}
