//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdAcademicWarning
    {
        public int ID { get; set; }
        public int StdSemesterID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> WarningNo { get; set; }
        public int WarningStatusID { get; set; }
        public int WarningTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<int> ActiveEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual StudentAcademic StudentAcademic { get; set; }
        public virtual WarningStatus WarningStatus { get; set; }
        public virtual WarningType WarningType { get; set; }
        public virtual StdSemester StdSemester { get; set; }
    }
}
