//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdSemester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StdSemester()
        {
            this.StdAcademicWarning = new HashSet<StdAcademicWarning>();
            this.StdSection = new HashSet<StdSection>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public int SemesterStatusID { get; set; }
        public Nullable<int> SemesterRegisteredHours { get; set; }
        public Nullable<int> SemesterRichnessHour { get; set; }
        public Nullable<int> SemesterFailedHour { get; set; }
        public Nullable<int> SemesterCumulativeRegisteredHours { get; set; }
        public Nullable<double> SemesterGPA { get; set; }
        public Nullable<double> SemesterCumulativeGPA { get; set; }
        public Nullable<int> SemesterCumulativeHours { get; set; }
        public Nullable<double> SemesterGraduateGpa { get; set; }
        public Nullable<int> SemesterPlanSucceedHour { get; set; }
        public Nullable<double> SemesterCumulativeGraduateGPA { get; set; }
        public Nullable<int> SemesterCumulativeGraduateHours { get; set; }
        public int CopyNo { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<int> RegisterStudentID { get; set; }
        public Nullable<int> RegisterEmployeeID { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public Nullable<int> ChangeStatusStudentID { get; set; }
        public Nullable<int> ChangeStatusEmployeeID { get; set; }
        public Nullable<System.DateTime> CopyNoDate { get; set; }
        public Nullable<int> CopyNoEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteStudentID { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual SemesterStatus SemesterStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdAcademicWarning> StdAcademicWarning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSection> StdSection { get; set; }
        public virtual StudentAcademic StudentAcademic { get; set; }
    }
}
