//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StdSection()
        {
            this.Mark = new HashSet<Mark>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public int StdSemesterID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> CourseHours { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> CourseStatusID { get; set; }
        public Nullable<bool> IsRemedialCourse { get; set; }
        public Nullable<int> TransWith { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> ScholarshipID { get; set; }
        public string ETransWithCourseName { get; set; }
        public Nullable<int> ETransWithCourseHours { get; set; }
        public Nullable<int> ITransWithCourseID { get; set; }
        public Nullable<int> ITransWithCourseHours { get; set; }
        public bool IsITransCourse { get; set; }
        public Nullable<int> StdInternalTransformationID { get; set; }
        public Nullable<int> RStdSectionID { get; set; }
        public Nullable<int> MidtermExamSectionID { get; set; }
        public Nullable<int> EMidtermExamSectionID { get; set; }
        public Nullable<int> FinalExamSectionID { get; set; }
        public Nullable<int> EFinalExamSectionID { get; set; }
        public bool Accreditation { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> RegisterStudentID { get; set; }
        public Nullable<int> RegisterEmployeeID { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public Nullable<int> ChangeStatusStudentID { get; set; }
        public Nullable<int> ChangeStatusEmployeeID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> TransEmployeeID { get; set; }
        public Nullable<System.DateTime> ITransDate { get; set; }
        public Nullable<int> ITransEmployeeID { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> AccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteStudentID { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual FinalExamSection FinalExamSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Mark { get; set; }
        public virtual StudentAcademic StudentAcademic { get; set; }
        public virtual MidtermExamSection MidtermExamSection { get; set; }
        public virtual StdSemester StdSemester { get; set; }
        public virtual Section Section { get; set; }
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
    }
}
