//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicLog
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PrevStudiedHour { get; set; }
        public Nullable<int> NewStudiedHour { get; set; }
        public Nullable<int> PrevSucceedHour { get; set; }
        public Nullable<int> NewSucceedHour { get; set; }
        public Nullable<int> PrevPlanSucceedHour { get; set; }
        public Nullable<int> NewPlanSucceedHour { get; set; }
        public Nullable<int> PrevStudyLevelID { get; set; }
        public Nullable<int> NewStudyLevelID { get; set; }
        public Nullable<decimal> PrevGPAUniversity { get; set; }
        public Nullable<decimal> NewGPAUniversity { get; set; }
        public Nullable<decimal> PrevGPAGraduate { get; set; }
        public Nullable<decimal> NewGPAGraduate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertEmployeeID { get; set; }
    }
}
