//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSuspended
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SSConditionID { get; set; }
        public string OtherCondition { get; set; }
        public string SuspendedDetails { get; set; }
        public bool SuspendedStatus { get; set; }
        public System.DateTime SuspendedDate { get; set; }
        public int SuspendedDepartmentID { get; set; }
        public int SuspendedEmployeeID { get; set; }
        public string UnSuspendedDetails { get; set; }
        public Nullable<System.DateTime> UnSuspendedDate { get; set; }
        public Nullable<int> UnSuspendedEmployeeID { get; set; }
    
        public virtual StudentAcademic StudentAcademic { get; set; }
    }
}
