//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentAcademic()
        {
            this.StdSection = new HashSet<StdSection>();
            this.StdAcademicWarning = new HashSet<StdAcademicWarning>();
            this.StudentSuspended = new HashSet<StudentSuspended>();
            this.StdStatus = new HashSet<StdStatus>();
            this.StdSemester = new HashSet<StdSemester>();
            this.StudentVolunteer = new HashSet<StudentVolunteer>();
        }
    
        public int StudentID { get; set; }
        public int StudentNo { get; set; }
        public Nullable<int> StudentTypeID { get; set; }
        public Nullable<int> IsraStudentTypeID { get; set; }
        public Nullable<int> RegisterSemesterID { get; set; }
        public Nullable<int> StudentStatusID2 { get; set; }
        public int ProgramID { get; set; }
        public byte[] StudentImage { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> FileNumSerial { get; set; }
        public Nullable<bool> IsValidImage { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DepartID1 { get; set; }
        public Nullable<int> DepartID2 { get; set; }
        public Nullable<int> DepartID3 { get; set; }
        public Nullable<int> PlaceOfStudyID { get; set; }
        public string TawjehyNo { get; set; }
        public Nullable<int> TawjehyTypeID { get; set; }
        public string TawjehyYear { get; set; }
        public decimal TawjehyGPA { get; set; }
        public string TawjehyCountry { get; set; }
        public string TawjehySchool { get; set; }
        public string OldUniversity { get; set; }
        public string OldDepartment { get; set; }
        public string OldUniversityGPA { get; set; }
        public Nullable<int> OldUniversityHours { get; set; }
        public string ShamelRate { get; set; }
        public string ExpertYears { get; set; }
        public Nullable<bool> IsRemedialCourses { get; set; }
        public decimal GPAGraduate { get; set; }
        public decimal GPAUniversity { get; set; }
        public decimal BITransGPAGraduate { get; set; }
        public decimal BITransGPAUniversity { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<int> StudiedHour { get; set; }
        public Nullable<int> SucceedHour { get; set; }
        public Nullable<int> PlanSucceedHour { get; set; }
        public int StudyLevel { get; set; }
        public int GraduationStatusID { get; set; }
        public Nullable<int> BITransStudiedHour { get; set; }
        public Nullable<int> BITransSucceedHour { get; set; }
        public Nullable<int> BITransPlanSucceedHour { get; set; }
        public int BITransStudyLevel { get; set; }
        public bool AppAccreditation { get; set; }
        public Nullable<int> AdmissionDepartmentID { get; set; }
        public Nullable<bool> AdmissionAccreditation { get; set; }
        public Nullable<System.DateTime> AdmissionAccreditationDate { get; set; }
        public Nullable<int> AdmissionEmployeeID { get; set; }
        public bool IsRefusal { get; set; }
        public string RefusalNotes { get; set; }
        public Nullable<System.DateTime> RefusalDate { get; set; }
        public Nullable<int> RefusalEmployeeID { get; set; }
        public bool IsAdmissionReturn { get; set; }
        public string AdmissionReturnNotes { get; set; }
        public Nullable<System.DateTime> AdmissionReturnDate { get; set; }
        public Nullable<int> AdmissionReturnEmployeeID { get; set; }
        public bool IsReadUnRole { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateStudentID { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteStudentID { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public string ChangeTypeNote { get; set; }
        public Nullable<System.DateTime> ChangeTypeDate { get; set; }
        public Nullable<int> ChangeTypeEmployeeID { get; set; }
        public Nullable<int> CurrentWarningNo { get; set; }
        public int RichnessHour { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public int TransformationHours { get; set; }
        public int OldUniversityTransformationHours { get; set; }
        public int VolunteerHours { get; set; }
        public bool IsVolunteerDone { get; set; }
        public string InGraduationCeremony { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Program Program { get; set; }
        public virtual StudentTypes StudentTypes { get; set; }
        public virtual StudyLevel StudyLevel1 { get; set; }
        public virtual StudentAcademic StudentAcademic1 { get; set; }
        public virtual StudentAcademic StudentAcademic2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSection> StdSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdAcademicWarning> StdAcademicWarning { get; set; }
        public virtual GraduationStatus GraduationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSuspended> StudentSuspended { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdStatus> StdStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdSemester> StdSemester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentVolunteer> StudentVolunteer { get; set; }
        public virtual StudentPersonal StudentPersonal { get; set; }
    }
}
