//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentVolunteer
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public int VolunteerTypeID { get; set; }
        public int VolunteerCategoryID { get; set; }
        public string VolunteerCategoryName { get; set; }
        public string OrganizationName { get; set; }
        public int OrganizationHour { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public bool IsAccept { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<int> AcceptEmployeeID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual StudentAcademic StudentAcademic { get; set; }
        public virtual VolunteerCategory VolunteerCategory { get; set; }
        public virtual VolunteerType VolunteerType { get; set; }
    }
}
