//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsView
    {
        public int ID { get; set; }
        public string StudentNo { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public bool Accreditation { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> StudentTypeID { get; set; }
        public Nullable<int> StudentStatusID { get; set; }
        public Nullable<decimal> GPAUniversity { get; set; }
        public string FileNumber { get; set; }
        public Nullable<decimal> GPAGraduate { get; set; }
        public Nullable<int> StudiedHour { get; set; }
        public Nullable<int> SucceedHour { get; set; }
        public Nullable<int> PlanSucceedHour { get; set; }
        public Nullable<int> StudyLevel { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<bool> StdCardRecieved { get; set; }
        public Nullable<bool> StdBagRecieved { get; set; }
        public Nullable<bool> StdCertificateRecieved { get; set; }
        public decimal Balance { get; set; }
    }
}
