//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaAcademic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPersonal
    {
        public int StudentID { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public string EnFirstName { get; set; }
        public string EnSecoundName { get; set; }
        public string EnThirdName { get; set; }
        public string EnFamilyName { get; set; }
        public string SSN { get; set; }
        public string Passport { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> CNationalityID { get; set; }
        public Nullable<int> CReligionID { get; set; }
        public string MotherName { get; set; }
        public string FatherSSN { get; set; }
        public Nullable<int> CStatusID { get; set; }
        public string NextSSN { get; set; }
        public int Gender { get; set; }
        public string SuperiorSSN { get; set; }
        public Nullable<int> CSuperiorLink { get; set; }
        public string SuperiorLink { get; set; }
        public string SuperiorName { get; set; }
        public string SuperiorAddress { get; set; }
        public Nullable<int> CSuperiorJopID { get; set; }
        public string SuperiorJop { get; set; }
        public string SuperiorPlaceJop { get; set; }
        public string SuperiorMobile { get; set; }
        public string SuperiorPhone { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> GovernoratesID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string HomeNo { get; set; }
        public string AddressDetails { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> CHealthStatusID { get; set; }
        public string DiseaseType { get; set; }
        public Nullable<bool> Disability { get; set; }
        public string DisabilityStatus { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Governorates Governorates { get; set; }
        public virtual StudentAcademic StudentAcademic { get; set; }
    }
}
