//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.Transaction = new HashSet<Transaction>();
            this.Voucher = new HashSet<Voucher>();
            this.StudentScholarship = new HashSet<StudentScholarship>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string ArName { get; set; }
        public string SpecialArName { get; set; }
        public string EnName { get; set; }
        public string FGroup { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public int CDType { get; set; }
        public int RVType { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public Nullable<int> SpecialActionTypeID { get; set; }
        public bool IsScholarship { get; set; }
        public Nullable<bool> IsLoan { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScholarship> StudentScholarship { get; set; }
    }
}
