//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpRequest
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> HelpType { get; set; }
        public Nullable<int> FamilyCountNo { get; set; }
        public Nullable<int> UnivStudentNo { get; set; }
        public Nullable<int> FamilySchoolNo { get; set; }
        public Nullable<int> SpecialNeedsNo { get; set; }
        public string FatherWork { get; set; }
        public string MotherWork { get; set; }
        public Nullable<bool> IsPerentDead { get; set; }
        public string FamilyIncome { get; set; }
        public Nullable<int> SocialCaseType { get; set; }
        public Nullable<int> HouseType { get; set; }
        public string RentValue { get; set; }
        public string FurnitureStatus { get; set; }
        public string BulidingType { get; set; }
        public string BulidingStatus { get; set; }
        public string BulidingArea { get; set; }
        public string HouseDescription { get; set; }
        public Nullable<int> HouseNature { get; set; }
        public Nullable<int> ResidencePlace { get; set; }
        public string Others { get; set; }
        public Nullable<bool> IsBenefit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> TypeRequestID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
