//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallmentOrder()
        {
            this.StudentInstallment = new HashSet<StudentInstallment>();
        }
    
        public int ID { get; set; }
        public int SemesterID { get; set; }
        public int StudentID { get; set; }
        public int NumOfHours { get; set; }
        public double PaidAmount { get; set; }
        public double RemainingAmount { get; set; }
        public bool Accreditation { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> AccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<int> GrantPercentage { get; set; }
        public Nullable<int> LastFinancialPayment { get; set; }
        public bool AffairsManagerAccreditation { get; set; }
        public Nullable<System.DateTime> AffairsManagerAccreditationDate { get; set; }
        public Nullable<int> AffairsManagerAccreditationEmpID { get; set; }
        public bool LoansDivisionAccerdiation { get; set; }
        public Nullable<System.DateTime> LoansDivisionAccerdiationDate { get; set; }
        public Nullable<int> LoansDivisionAccerdiationEmpID { get; set; }
        public bool AcademicAccerdiation { get; set; }
        public Nullable<System.DateTime> AcademicAccerdiationDate { get; set; }
        public Nullable<int> AcademicAccerdiationEmpID { get; set; }
        public bool ManagmentAccreditation { get; set; }
        public Nullable<int> ManagmentAccreditationEmpID { get; set; }
        public Nullable<System.DateTime> ManagmentAccreditationDate { get; set; }
    
        public virtual StudentData StudentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInstallment> StudentInstallment { get; set; }
    }
}
