//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsraDataEntities : DbContext
    {
        public IsraDataEntities()
            : base("name=IsraDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InstallmentOrder> InstallmentOrder { get; set; }
        public virtual DbSet<StudentInstallment> StudentInstallment { get; set; }
        public virtual DbSet<StudentData> StudentData { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionType> ActionType { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<CurrencyPrice> CurrencyPrice { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<VoucherDetails> VoucherDetails { get; set; }
        public virtual DbSet<VoucherType> VoucherType { get; set; }
        public virtual DbSet<StudentScholarship> StudentScholarship { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransaction { get; set; }
        public virtual DbSet<AccountVoucher> AccountVoucher { get; set; }
        public virtual DbSet<AccountVoucherDetails> AccountVoucherDetails { get; set; }
        public virtual DbSet<HelpRequest> HelpRequest { get; set; }
        public virtual DbSet<StringNumber> StringNumber { get; set; }
        public virtual DbSet<StudentBankInstallment> StudentBankInstallment { get; set; }
        public virtual DbSet<StudentHelps> StudentHelps { get; set; }
        public virtual DbSet<StudentLoan> StudentLoan { get; set; }
        public virtual DbSet<StudentSocialSolidarity> StudentSocialSolidarity { get; set; }
    }
}
