//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHelps
    {
        public int ID { get; set; }
        public Nullable<int> HelpRequestID { get; set; }
        public string HelpType { get; set; }
        public string HelpOrganization { get; set; }
        public string HelpValue { get; set; }
    }
}
