//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBankInstallment
    {
        public int ID { get; set; }
        public int SemesterID { get; set; }
        public int StudentID { get; set; }
        public int RegesterHour { get; set; }
        public int BankBranchID { get; set; }
        public bool HeadAccreditation { get; set; }
        public bool MangerAccreditation { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertStudentID { get; set; }
        public Nullable<System.DateTime> HeadAccreditationDate { get; set; }
        public Nullable<int> HeadAccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> MangerAccreditationDate { get; set; }
        public Nullable<int> MangerAccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
