//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AccreditationDepartment> AccreditationDepartment { get; set; }
    public virtual DbSet<AccreditationSeries> AccreditationSeries { get; set; }
    public virtual DbSet<AccreditationSeriesOrder> AccreditationSeriesOrder { get; set; }
    public virtual DbSet<AccreditationType> AccreditationType { get; set; }
    public virtual DbSet<AdmissionConditions> AdmissionConditions { get; set; }
    public virtual DbSet<Advertisement> Advertisement { get; set; }
    public virtual DbSet<Attendance> Attendance { get; set; }
    public virtual DbSet<Block> Block { get; set; }
    public virtual DbSet<BlockSection> BlockSection { get; set; }
    public virtual DbSet<Book> Book { get; set; }
    public virtual DbSet<Branch> Branch { get; set; }
    public virtual DbSet<Building> Building { get; set; }
    public virtual DbSet<City> City { get; set; }
    public virtual DbSet<College> College { get; set; }
    public virtual DbSet<CollegeEmployee> CollegeEmployee { get; set; }
    public virtual DbSet<CollegeEmployeeOld> CollegeEmployeeOld { get; set; }
    public virtual DbSet<CollegePTEHours> CollegePTEHours { get; set; }
    public virtual DbSet<CollegeRoom> CollegeRoom { get; set; }
    public virtual DbSet<Conditions> Conditions { get; set; }
    public virtual DbSet<Constant> Constant { get; set; }
    public virtual DbSet<ConstantDetails> ConstantDetails { get; set; }
    public virtual DbSet<Country> Country { get; set; }
    public virtual DbSet<Course> Course { get; set; }
    public virtual DbSet<CourseBook> CourseBook { get; set; }
    public virtual DbSet<CourseBookRequest> CourseBookRequest { get; set; }
    public virtual DbSet<CourseCategory> CourseCategory { get; set; }
    public virtual DbSet<CourseStatus> CourseStatus { get; set; }
    public virtual DbSet<CourseType> CourseType { get; set; }
    public virtual DbSet<Day> Day { get; set; }
    public virtual DbSet<Department> Department { get; set; }
    public virtual DbSet<DepartmentEmployee> DepartmentEmployee { get; set; }
    public virtual DbSet<DepartmentSection> DepartmentSection { get; set; }
    public virtual DbSet<EFinalExamSection> EFinalExamSection { get; set; }
    public virtual DbSet<ELearningVideo> ELearningVideo { get; set; }
    public virtual DbSet<ELearningVideoType> ELearningVideoType { get; set; }
    public virtual DbSet<EMidtermExamSection> EMidtermExamSection { get; set; }
    public virtual DbSet<EmployeeDetails> EmployeeDetails { get; set; }
    public virtual DbSet<EmployeeType> EmployeeType { get; set; }
    public virtual DbSet<ExamSection> ExamSection { get; set; }
    public virtual DbSet<ExamSectionDistribution> ExamSectionDistribution { get; set; }
    public virtual DbSet<ExceptionCategory> ExceptionCategory { get; set; }
    public virtual DbSet<ExceptionStudentCourse> ExceptionStudentCourse { get; set; }
    public virtual DbSet<ExceptionStudentGeneral> ExceptionStudentGeneral { get; set; }
    public virtual DbSet<ExceptionType> ExceptionType { get; set; }
    public virtual DbSet<FinalExamSection> FinalExamSection { get; set; }
    public virtual DbSet<FinalMarkIncomplete> FinalMarkIncomplete { get; set; }
    public virtual DbSet<Form> Form { get; set; }
    public virtual DbSet<FormAccreditationSeries> FormAccreditationSeries { get; set; }
    public virtual DbSet<ForStudentCard> ForStudentCard { get; set; }
    public virtual DbSet<Gender> Gender { get; set; }
    public virtual DbSet<Governorates> Governorates { get; set; }
    public virtual DbSet<GraduationStatus> GraduationStatus { get; set; }
    public virtual DbSet<HowKnow> HowKnow { get; set; }
    public virtual DbSet<Infraction> Infraction { get; set; }
    public virtual DbSet<InfractionType> InfractionType { get; set; }
    public virtual DbSet<Lecture> Lecture { get; set; }
    public virtual DbSet<LectureIrregular> LectureIrregular { get; set; }
    public virtual DbSet<Mark> Mark { get; set; }
    public virtual DbSet<MarkDeduction> MarkDeduction { get; set; }
    public virtual DbSet<MarkLog> MarkLog { get; set; }
    public virtual DbSet<MarkRevision> MarkRevision { get; set; }
    public virtual DbSet<MarkTitle> MarkTitle { get; set; }
    public virtual DbSet<MidtermExamSection> MidtermExamSection { get; set; }
    public virtual DbSet<Observers> Observers { get; set; }
    public virtual DbSet<ObserversHelper> ObserversHelper { get; set; }
    public virtual DbSet<OfferdCourse> OfferdCourse { get; set; }
    public virtual DbSet<OfferdCourseType> OfferdCourseType { get; set; }
    public virtual DbSet<OfferdPlanCourse> OfferdPlanCourse { get; set; }
    public virtual DbSet<OfficeHour> OfficeHour { get; set; }
    public virtual DbSet<PlaceOfStudy> PlaceOfStudy { get; set; }
    public virtual DbSet<Plan> Plan { get; set; }
    public virtual DbSet<PlanCourse> PlanCourse { get; set; }
    public virtual DbSet<PlanSemester> PlanSemester { get; set; }
    public virtual DbSet<PreRequest> PreRequest { get; set; }
    public virtual DbSet<Program> Program { get; set; }
    public virtual DbSet<ProgramEmployee> ProgramEmployee { get; set; }
    public virtual DbSet<ProgramLevel> ProgramLevel { get; set; }
    public virtual DbSet<PTEmployee> PTEmployee { get; set; }
    public virtual DbSet<Room> Room { get; set; }
    public virtual DbSet<RoomType> RoomType { get; set; }
    public virtual DbSet<Section> Section { get; set; }
    public virtual DbSet<SectionDepartment> SectionDepartment { get; set; }
    public virtual DbSet<SectionType> SectionType { get; set; }
    public virtual DbSet<Semester> Semester { get; set; }
    public virtual DbSet<SemesterStatus> SemesterStatus { get; set; }
    public virtual DbSet<SemesterType> SemesterType { get; set; }
    public virtual DbSet<Setting> Setting { get; set; }
    public virtual DbSet<SMSArchive> SMSArchive { get; set; }
    public virtual DbSet<StdAcademicWarning> StdAcademicWarning { get; set; }
    public virtual DbSet<StdDocument> StdDocument { get; set; }
    public virtual DbSet<StdDocumentType> StdDocumentType { get; set; }
    public virtual DbSet<StdGraduateAvowal> StdGraduateAvowal { get; set; }
    public virtual DbSet<StdHowKnow> StdHowKnow { get; set; }
    public virtual DbSet<StdInfraction> StdInfraction { get; set; }
    public virtual DbSet<StdInternalEquation> StdInternalEquation { get; set; }
    public virtual DbSet<StdInternalTransformation> StdInternalTransformation { get; set; }
    public virtual DbSet<StdMessage> StdMessage { get; set; }
    public virtual DbSet<StdSection> StdSection { get; set; }
    public virtual DbSet<StdSemester> StdSemester { get; set; }
    public virtual DbSet<StdStatus> StdStatus { get; set; }
    public virtual DbSet<StdTransformationCourses> StdTransformationCourses { get; set; }
    public virtual DbSet<StudentAcademic> StudentAcademic { get; set; }
    public virtual DbSet<StudentAcademicCalendar> StudentAcademicCalendar { get; set; }
    public virtual DbSet<StudentAcademicLog> StudentAcademicLog { get; set; }
    public virtual DbSet<StudentBook> StudentBook { get; set; }
    public virtual DbSet<StudentBranch> StudentBranch { get; set; }
    public virtual DbSet<StudentCondition> StudentCondition { get; set; }
    public virtual DbSet<StudentCourse> StudentCourse { get; set; }
    public virtual DbSet<StudentFromAccountAPI> StudentFromAccountAPI { get; set; }
    public virtual DbSet<StudentPersonal> StudentPersonal { get; set; }
    public virtual DbSet<StudentProblems> StudentProblems { get; set; }
    public virtual DbSet<StudentsActivities> StudentsActivities { get; set; }
    public virtual DbSet<StudentsFreeFromTwentyPercCondAPI> StudentsFreeFromTwentyPercCondAPI { get; set; }
    public virtual DbSet<StudentStatus> StudentStatus { get; set; }
    public virtual DbSet<StudentSuspended> StudentSuspended { get; set; }
    public virtual DbSet<StudentSuspendedCondition> StudentSuspendedCondition { get; set; }
    public virtual DbSet<StudentTypes> StudentTypes { get; set; }
    public virtual DbSet<StudentVolunteer> StudentVolunteer { get; set; }
    public virtual DbSet<StudyLevel> StudyLevel { get; set; }
    public virtual DbSet<Syllabus> Syllabus { get; set; }
    public virtual DbSet<SyllabusAccreditation> SyllabusAccreditation { get; set; }
    public virtual DbSet<SyllabusActivity> SyllabusActivity { get; set; }
    public virtual DbSet<SyllabusBook> SyllabusBook { get; set; }
    public virtual DbSet<SyllabusDetailedDescription> SyllabusDetailedDescription { get; set; }
    public virtual DbSet<SyllabusEvaluation> SyllabusEvaluation { get; set; }
    public virtual DbSet<SyllabusGoal> SyllabusGoal { get; set; }
    public virtual DbSet<SyllabusOutcome> SyllabusOutcome { get; set; }
    public virtual DbSet<SyllabusReference> SyllabusReference { get; set; }
    public virtual DbSet<TawjehyType> TawjehyType { get; set; }
    public virtual DbSet<TransformationReason> TransformationReason { get; set; }
    public virtual DbSet<VolunteerCategory> VolunteerCategory { get; set; }
    public virtual DbSet<VolunteerType> VolunteerType { get; set; }
    public virtual DbSet<WarningStatus> WarningStatus { get; set; }
    public virtual DbSet<WarningType> WarningType { get; set; }
    public virtual DbSet<WorkMark> WorkMark { get; set; }
    public virtual DbSet<WorkMarkAccreditation> WorkMarkAccreditation { get; set; }
    public virtual DbSet<WorkMarkRevision> WorkMarkRevision { get; set; }
    public virtual DbSet<WorkMarkTitle> WorkMarkTitle { get; set; }
    public virtual DbSet<CourseOptionalCourses> CourseOptionalCourses { get; set; }
    public virtual DbSet<ExamSectionEmployee> ExamSectionEmployee { get; set; }
    public virtual DbSet<UnSuspendEmp> UnSuspendEmp { get; set; }
}
