//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodyDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodyDetails()
        {
            this.RepositoryCustody = new HashSet<RepositoryCustody>();
        }
    
        public int Id { get; set; }
        public int CustodyTypeId { get; set; }
        public System.DateTime CustodyDate { get; set; }
        public Nullable<int> RepositoryDepartmentId { get; set; }
        public int DepartmentId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> ToEmployeeId { get; set; }
        public int MaterialId { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
        public int RequestStatusId { get; set; }
        public bool CustodyStatus { get; set; }
        public Nullable<System.DateTime> DateOfReturnCustody { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<int> InsertEmployeeId { get; set; }
    
        public virtual CustodyType CustodyType { get; set; }
        public virtual Material Material { get; set; }
        public virtual RepositoryDepartment RepositoryDepartment { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepositoryCustody> RepositoryCustody { get; set; }
    }
}
