//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetails
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public int RepositoryDepartmentId { get; set; }
        public Nullable<int> ToRepositoryDepartmentId { get; set; }
        public int MaterialId { get; set; }
        public int UnitId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> QuantityAfterInventory { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Notes { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<int> InsertEmployeeId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MaterialUnit MaterialUnit { get; set; }
        public virtual RepositoryDepartment RepositoryDepartment { get; set; }
        public virtual RepositoryDepartment RepositoryDepartment1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
