//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsraaHumanResourceEntities : DbContext
    {
        public IsraaHumanResourceEntities()
            : base("name=IsraaHumanResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AccreditationStatu> AccreditationStatus { get; set; }
        public virtual DbSet<AttendanceDaily> AttendanceDailies { get; set; }
        public virtual DbSet<AttendanceExit> AttendanceExits { get; set; }
        public virtual DbSet<AttendanceExitType> AttendanceExitTypes { get; set; }
        public virtual DbSet<AttendanceFingerprint> AttendanceFingerprints { get; set; }
        public virtual DbSet<AttendanceFormat> AttendanceFormats { get; set; }
        public virtual DbSet<AttendanceFormatDetail> AttendanceFormatDetails { get; set; }
        public virtual DbSet<AttendanceInstructor> AttendanceInstructors { get; set; }
        public virtual DbSet<AttendanceInstructorStatu> AttendanceInstructorStatus { get; set; }
        public virtual DbSet<AttendanceInstructorTimeOut> AttendanceInstructorTimeOuts { get; set; }
        public virtual DbSet<AttendanceMonthly> AttendanceMonthlies { get; set; }
        public virtual DbSet<AttendanceTimeOut> AttendanceTimeOuts { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankAcount> BankAcounts { get; set; }
        public virtual DbSet<BasicSalary> BasicSalaries { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<BonusType> BonusTypes { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Cader> Caders { get; set; }
        public virtual DbSet<CaderDegree> CaderDegrees { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContractInstructor> ContractInstructors { get; set; }
        public virtual DbSet<ContractStatu> ContractStatus { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<DayStatu> DayStatus { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<DeductionStatu> DeductionStatus { get; set; }
        public virtual DbSet<DeductionType> DeductionTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentType> DepartmentTypes { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<EmpCategory> EmpCategories { get; set; }
        public virtual DbSet<EmpEmploymentType> EmpEmploymentTypes { get; set; }
        public virtual DbSet<EmployeeAppointmentDecision> EmployeeAppointmentDecisions { get; set; }
        public virtual DbSet<EmployeeAttendanceFormat> EmployeeAttendanceFormats { get; set; }
        public virtual DbSet<EmployeeBank> EmployeeBanks { get; set; }
        public virtual DbSet<EmployeeBonu> EmployeeBonus { get; set; }
        public virtual DbSet<EmployeeCategory> EmployeeCategories { get; set; }
        public virtual DbSet<EmployeeContract> EmployeeContracts { get; set; }
        public virtual DbSet<EmployeeContractRenew> EmployeeContractRenews { get; set; }
        public virtual DbSet<EmployeeDeduction> EmployeeDeductions { get; set; }
        public virtual DbSet<EmployeeDocument> EmployeeDocuments { get; set; }
        public virtual DbSet<EmployeeFacebook> EmployeeFacebooks { get; set; }
        public virtual DbSet<EmployeeFacebookPost> EmployeeFacebookPosts { get; set; }
        public virtual DbSet<EmployeeFamily> EmployeeFamilies { get; set; }
        public virtual DbSet<EmployeeIdentifier> EmployeeIdentifiers { get; set; }
        public virtual DbSet<EmployeeLanguage> EmployeeLanguages { get; set; }
        public virtual DbSet<EmployeeMedicalCheckUp> EmployeeMedicalCheckUps { get; set; }
        public virtual DbSet<EmployeeMessage> EmployeeMessages { get; set; }
        public virtual DbSet<EmployeePersonal> EmployeePersonals { get; set; }
        public virtual DbSet<EmployeePlacement> EmployeePlacements { get; set; }
        public virtual DbSet<EmployeePracticalExperience> EmployeePracticalExperiences { get; set; }
        public virtual DbSet<EmployeeQualification> EmployeeQualifications { get; set; }
        public virtual DbSet<EmployeeResearch> EmployeeResearches { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual DbSet<EmployeeSkill> EmployeeSkills { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeTrainingCourse> EmployeeTrainingCourses { get; set; }
        public virtual DbSet<EmployeeVacation> EmployeeVacations { get; set; }
        public virtual DbSet<EmployeeVacationBalance> EmployeeVacationBalances { get; set; }
        public virtual DbSet<EmployeeVacationSickReport> EmployeeVacationSickReports { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<EmpStatu> EmpStatus { get; set; }
        public virtual DbSet<FingerprintType> FingerprintTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Governorate> Governorates { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<HolidayType> HolidayTypes { get; set; }
        public virtual DbSet<InstructorType> InstructorTypes { get; set; }
        public virtual DbSet<InstructorTypeHourPrice> InstructorTypeHourPrices { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobCategory> JobCategories { get; set; }
        public virtual DbSet<JobPersonal> JobPersonals { get; set; }
        public virtual DbSet<JobRequirement> JobRequirements { get; set; }
        public virtual DbSet<JobTask> JobTasks { get; set; }
        public virtual DbSet<JobTaskPointer> JobTaskPointers { get; set; }
        public virtual DbSet<JobTerm> JobTerms { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<KnowLevel> KnowLevels { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LateType> LateTypes { get; set; }
        public virtual DbSet<LogEmployeeVacationBalance> LogEmployeeVacationBalances { get; set; }
        public virtual DbSet<MachineFingerprint> MachineFingerprints { get; set; }
        public virtual DbSet<ManualFingerprint> ManualFingerprints { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<MonthDay> MonthDays { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<NotificationFlag> NotificationFlags { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PersonStatu> PersonStatus { get; set; }
        public virtual DbSet<PlacementStatu> PlacementStatus { get; set; }
        public virtual DbSet<PlacementType> PlacementTypes { get; set; }
        public virtual DbSet<QualificationType> QualificationTypes { get; set; }
        public virtual DbSet<RelativeType> RelativeTypes { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<SalaryBox> SalaryBoxes { get; set; }
        public virtual DbSet<SalaryBoxType> SalaryBoxTypes { get; set; }
        public virtual DbSet<SkillType> SkillTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VacationBalanceYear> VacationBalanceYears { get; set; }
        public virtual DbSet<VacationPlace> VacationPlaces { get; set; }
        public virtual DbSet<VacationType> VacationTypes { get; set; }
        public virtual DbSet<EmployeeEmergencyInfo> EmployeeEmergencyInfoes { get; set; }
        public virtual DbSet<Sheet1_> Sheet1_ { get; set; }
    }
}
