//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaPermissions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string StudentNo { get; set; }
        public string Password { get; set; }
        public bool Accreditation { get; set; }
        public decimal Balance { get; set; }
        public Nullable<decimal> RegBalance { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> AccreditationEmployeeID { get; set; }
        public Nullable<int> IsActiveEmployeeID { get; set; }
        public string IsActiveNotes { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateStudentID { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<bool> StdCardRecieved { get; set; }
        public Nullable<bool> StdBagRecieved { get; set; }
        public Nullable<bool> StdCertificateRecieved { get; set; }
    }
}
