//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllEmployees
    {
        public int ID { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public string Gender { get; set; }
        public string EmployeeImageURL { get; set; }
        public string Mobile { get; set; }
        public string UniversityEmail { get; set; }
        public string EmployeeJobTitle { get; set; }
        public string EmployeeDepartment { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public Nullable<int> EmployeeEmploymentTypeID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Street { get; set; }
    }
}
