//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceMonthly
    {
        public int ID { get; set; }
        public int Year { get; set; }
        public int MonthID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> MonthDateFrom { get; set; }
        public Nullable<System.DateTime> MonthDateTo { get; set; }
        public int MonthDays { get; set; }
        public int HolidayDays { get; set; }
        public int VacationDays { get; set; }
        public int AttendanceDays { get; set; }
        public int WeekHolidayDays { get; set; }
        public int AbsenceDays { get; set; }
        public int PostOutMinutes { get; set; }
        public int LateMinutes { get; set; }
        public int ExitMinutes1 { get; set; }
        public int ExitMinutes2 { get; set; }
        public int ExitMinutes3 { get; set; }
        public int AvgDefualtMinutes { get; set; }
        public int OutDays { get; set; }
        public int BalanceOutMinutes { get; set; }
        public Nullable<int> BalanceRemainingDays { get; set; }
        public int BalanceChangeDays { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<bool> DeductedFromSalary { get; set; }
    }
}
