//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceExit
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> EmployeeDMID { get; set; }
        public int AttendanceExitTypeID { get; set; }
        public int DeductionStatusID { get; set; }
        public System.DateTime ExitDate { get; set; }
        public Nullable<System.TimeSpan> ExpectedTimeFrom { get; set; }
        public Nullable<System.TimeSpan> ExpectedTimeTo { get; set; }
        public Nullable<System.TimeSpan> ActualTimeFrom { get; set; }
        public Nullable<System.TimeSpan> ActualTimeTo { get; set; }
        public string ExitReason { get; set; }
        public string Mobile { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ExitMinutes { get; set; }
        public Nullable<bool> DMAccreditation { get; set; }
        public string UpdateDetails { get; set; }
        public string DeleteReason { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> AccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<int> DirectManagerAccreditationStatusId { get; set; }
        public Nullable<int> DirectMangerAccredationDate { get; set; }
        public Nullable<int> HumanResourceEmployeeId { get; set; }
        public Nullable<int> HumanResourceAccreditationStatusId { get; set; }
        public Nullable<System.DateTime> HumanResourceAccredationDate { get; set; }
        public string HumanResourceNote { get; set; }
    
        public virtual AccreditationStatus AccreditationStatus { get; set; }
        public virtual AccreditationStatus AccreditationStatus1 { get; set; }
        public virtual AttendanceExitType AttendanceExitType { get; set; }
        public virtual DeductionStatus DeductionStatus { get; set; }
        public virtual EmployeePersonal EmployeePersonal { get; set; }
        public virtual EmployeePersonal EmployeePersonal1 { get; set; }
        public virtual EmployeePersonal EmployeePersonal2 { get; set; }
    }
}
