//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDaily
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.TimeSpan AttendanceFrom { get; set; }
        public Nullable<System.TimeSpan> AttendanceTo { get; set; }
        public Nullable<System.TimeSpan> DefaultFrom { get; set; }
        public Nullable<System.TimeSpan> DefaultTo { get; set; }
        public Nullable<int> EmpAttFormatID { get; set; }
        public Nullable<int> AttFormatDetailsID { get; set; }
        public Nullable<int> DefaultMinutes { get; set; }
        public Nullable<int> AttendanceMinutes { get; set; }
        public Nullable<int> ExitMinutes { get; set; }
        public Nullable<int> ExitMinutes1 { get; set; }
        public Nullable<int> ExitMinutes2 { get; set; }
        public Nullable<int> ExitMinutes3 { get; set; }
        public Nullable<int> MorningLateMinutes { get; set; }
        public Nullable<int> EveningLateMinutes { get; set; }
        public Nullable<int> OtherLateMinutes { get; set; }
        public int DayStatusID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> ManualFingerID1 { get; set; }
        public Nullable<int> ManualFingerID2 { get; set; }
    
        public virtual AttendanceDaily AttendanceDaily1 { get; set; }
        public virtual AttendanceDaily AttendanceDaily2 { get; set; }
        public virtual AttendanceFormatDetails AttendanceFormatDetails { get; set; }
        public virtual DayStatus DayStatus { get; set; }
        public virtual EmployeeAttendanceFormat EmployeeAttendanceFormat { get; set; }
        public virtual EmployeePersonal EmployeePersonal { get; set; }
    }
}
