//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractInstructor
    {
        public int ID { get; set; }
        public int SemesterID { get; set; }
        public int InstructorID { get; set; }
        public int InstructorTypeID { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<double> LectureHours { get; set; }
        public Nullable<double> InstructorHours { get; set; }
        public Nullable<double> InstructorCost { get; set; }
        public double HourPrice { get; set; }
        public int CurrencyID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
