//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFamily
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int RelativeTypeID { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public int GenderID { get; set; }
        public string SSN { get; set; }
        public string PlaceOfBirth { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int MaritalStatusID { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public int PersonStatusID { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public string UpdateDetails { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual EmployeePersonal EmployeePersonal { get; set; }
    }
}
