//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeReportData
    {
        public int ID { get; set; }
        public string EmployeeNo { get; set; }
        public string Branch { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> GovernorateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SSN { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> ChildrensCount { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string UniversityEmail { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<System.DateTime> StartDateEmpStatus { get; set; }
        public Nullable<System.DateTime> EndDateEmpStatus { get; set; }
        public Nullable<int> JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string College { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public Nullable<int> EmployeeDManagerID { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public string EmploymentType { get; set; }
        public Nullable<System.DateTime> StartDateEmpEmploymentType { get; set; }
        public Nullable<System.DateTime> EndDateEmpEmploymentType { get; set; }
        public string AttendanceDefault { get; set; }
        public Nullable<int> AttendanceFormatID { get; set; }
        public Nullable<int> CaderID { get; set; }
        public string Cader { get; set; }
        public Nullable<int> PlacementStatusID { get; set; }
        public string PlacementStatus { get; set; }
        public Nullable<int> PlacementTypeID { get; set; }
        public string PlacementType { get; set; }
        public Nullable<int> QualificationTypeID { get; set; }
        public string Qualification { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> QualificationYear { get; set; }
        public string QualificationUniversityName { get; set; }
        public string QualificationCountryName { get; set; }
        public string BasicSalary { get; set; }
        public string BasicSalaryCurrency { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> CollegeID { get; set; }
    }
}
