//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMessage
    {
        public int ID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Jawwal { get; set; }
        public string MessageBody { get; set; }
        public Nullable<bool> SendStatus { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
