//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContract
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int JobID { get; set; }
        public int ContractTypeID { get; set; }
        public int AttendanceTypeID { get; set; }
        public System.DateTime TestDateFrom { get; set; }
        public System.DateTime TestDateTo { get; set; }
        public System.DateTime DefaultDateFrom { get; set; }
        public System.DateTime DefaultDateTo { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<bool> IsAccredit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string UpdateDetails { get; set; }
        public Nullable<System.DateTime> AccreditDate { get; set; }
        public Nullable<int> AccreditEmployeeID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<int> FinishedEmployeeID { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public Nullable<int> CanceledEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
