//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFacebook
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string FacebookID { get; set; }
        public string FacebookName { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
