//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAppointmentDecision
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeNo { get; set; }
        public int DepartmentID { get; set; }
        public int JobID { get; set; }
        public int ContractTypeID { get; set; }
        public int QualificationTypeID { get; set; }
        public int GraduateYear { get; set; }
        public int GenderID { get; set; }
        public int MaritalStatusID { get; set; }
        public bool WifeStatus { get; set; }
        public double BasicSalary { get; set; }
        public int CurrencyID { get; set; }
        public int BankID { get; set; }
        public int BankNo { get; set; }
        public System.DateTime TestDateFrom { get; set; }
        public System.DateTime TestDateTo { get; set; }
        public System.DateTime DefaultDateFrom { get; set; }
        public System.DateTime DefaultDateTo { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public string UpdateDetails { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    }
}
