//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePlacement
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int JobID { get; set; }
        public int CaderID { get; set; }
        public int PlacementStatusID { get; set; }
        public int PlacementTypeID { get; set; }
        public Nullable<int> DManagerID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public string UpdateDetails { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
    
        public virtual Cader Cader { get; set; }
        public virtual Department Department { get; set; }
        public virtual PlacementStatus PlacementStatus { get; set; }
        public virtual PlacementType PlacementType { get; set; }
        public virtual Job Job { get; set; }
        public virtual EmployeePersonal EmployeePersonal { get; set; }
        public virtual EmployeePersonal EmployeePersonal1 { get; set; }
    }
}
