//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeePersonal()
        {
            this.AttendanceDaily = new HashSet<AttendanceDaily>();
            this.AttendanceExit = new HashSet<AttendanceExit>();
            this.AttendanceExit1 = new HashSet<AttendanceExit>();
            this.AttendanceExit2 = new HashSet<AttendanceExit>();
            this.EmpCategory = new HashSet<EmpCategory>();
            this.EmpEmploymentType = new HashSet<EmpEmploymentType>();
            this.EmployeeAttendanceFormat = new HashSet<EmployeeAttendanceFormat>();
            this.EmployeeFamily = new HashSet<EmployeeFamily>();
            this.EmployeePlacement = new HashSet<EmployeePlacement>();
            this.EmployeePlacement1 = new HashSet<EmployeePlacement>();
            this.EmployeePracticalExperience = new HashSet<EmployeePracticalExperience>();
            this.EmployeeQualification = new HashSet<EmployeeQualification>();
            this.EmployeeVacation = new HashSet<EmployeeVacation>();
            this.EmployeeVacation1 = new HashSet<EmployeeVacation>();
            this.EmpStatus = new HashSet<EmpStatus>();
            this.Notifications = new HashSet<Notifications>();
            this.Notifications1 = new HashSet<Notifications>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string ArNameTitle { get; set; }
        public string ArFirstName { get; set; }
        public string ArSecoundName { get; set; }
        public string ArThirdName { get; set; }
        public string ArFamilyName { get; set; }
        public string EnNameTitle { get; set; }
        public string EnFirstName { get; set; }
        public string EnSecoundName { get; set; }
        public string EnThirdName { get; set; }
        public string EnFamilyName { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string SSN { get; set; }
        public string Passport { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> GovernorateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string HomeNo { get; set; }
        public string AddressDetails { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string UniversityEmail { get; set; }
        public string UpdateDetails { get; set; }
        public Nullable<bool> IsFullTime { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> InstructorTypeID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDaily> AttendanceDaily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceExit> AttendanceExit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceExit> AttendanceExit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceExit> AttendanceExit2 { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpCategory> EmpCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpEmploymentType> EmpEmploymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAttendanceFormat> EmployeeAttendanceFormat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFamily> EmployeeFamily { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Governorate Governorate { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePlacement> EmployeePlacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePlacement> EmployeePlacement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePracticalExperience> EmployeePracticalExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeQualification> EmployeeQualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVacation> EmployeeVacation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVacation> EmployeeVacation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpStatus> EmpStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications1 { get; set; }
    }
}
