//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorTypeHourPrice
    {
        public int ID { get; set; }
        public int InstructorTypeID { get; set; }
        public double HourPrice { get; set; }
        public int CurrencyID { get; set; }
        public int ProgramID { get; set; }
    }
}
