//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsraaHumanResourceEntities : DbContext
    {
        public IsraaHumanResourceEntities()
            : base("name=IsraaHumanResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeReportData> EmployeeReportData { get; set; }
        public virtual DbSet<AccreditationStatus> AccreditationStatus { get; set; }
        public virtual DbSet<AttendanceDaily> AttendanceDaily { get; set; }
        public virtual DbSet<AttendanceExit> AttendanceExit { get; set; }
        public virtual DbSet<AttendanceExitType> AttendanceExitType { get; set; }
        public virtual DbSet<AttendanceFingerprint> AttendanceFingerprint { get; set; }
        public virtual DbSet<AttendanceFormat> AttendanceFormat { get; set; }
        public virtual DbSet<AttendanceFormatDetails> AttendanceFormatDetails { get; set; }
        public virtual DbSet<AttendanceInstructor> AttendanceInstructor { get; set; }
        public virtual DbSet<AttendanceInstructorStatus> AttendanceInstructorStatus { get; set; }
        public virtual DbSet<AttendanceInstructorTimeOut> AttendanceInstructorTimeOut { get; set; }
        public virtual DbSet<AttendanceMonthly> AttendanceMonthly { get; set; }
        public virtual DbSet<AttendanceTimeOut> AttendanceTimeOut { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankAcount> BankAcount { get; set; }
        public virtual DbSet<BasicSalary> BasicSalary { get; set; }
        public virtual DbSet<Bonus> Bonus { get; set; }
        public virtual DbSet<BonusType> BonusType { get; set; }
        public virtual DbSet<Cader> Cader { get; set; }
        public virtual DbSet<CaderDegree> CaderDegree { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ContractInstructor> ContractInstructor { get; set; }
        public virtual DbSet<ContractStatus> ContractStatus { get; set; }
        public virtual DbSet<ContractType> ContractType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<DayStatus> DayStatus { get; set; }
        public virtual DbSet<Deduction> Deduction { get; set; }
        public virtual DbSet<DeductionStatus> DeductionStatus { get; set; }
        public virtual DbSet<DeductionType> DeductionType { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentType> DepartmentType { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<EmpCategory> EmpCategory { get; set; }
        public virtual DbSet<EmpEmploymentType> EmpEmploymentType { get; set; }
        public virtual DbSet<EmployeeAppointmentDecision> EmployeeAppointmentDecision { get; set; }
        public virtual DbSet<EmployeeAttendanceFormat> EmployeeAttendanceFormat { get; set; }
        public virtual DbSet<EmployeeBank> EmployeeBank { get; set; }
        public virtual DbSet<EmployeeBonus> EmployeeBonus { get; set; }
        public virtual DbSet<EmployeeCategory> EmployeeCategory { get; set; }
        public virtual DbSet<EmployeeContract> EmployeeContract { get; set; }
        public virtual DbSet<EmployeeContractRenew> EmployeeContractRenew { get; set; }
        public virtual DbSet<EmployeeDeduction> EmployeeDeduction { get; set; }
        public virtual DbSet<EmployeeDocument> EmployeeDocument { get; set; }
        public virtual DbSet<EmployeeFacebook> EmployeeFacebook { get; set; }
        public virtual DbSet<EmployeeFacebookPost> EmployeeFacebookPost { get; set; }
        public virtual DbSet<EmployeeFamily> EmployeeFamily { get; set; }
        public virtual DbSet<EmployeeIdentifier> EmployeeIdentifier { get; set; }
        public virtual DbSet<EmployeeLanguage> EmployeeLanguage { get; set; }
        public virtual DbSet<EmployeeMedicalCheckUp> EmployeeMedicalCheckUp { get; set; }
        public virtual DbSet<EmployeeMessage> EmployeeMessage { get; set; }
        public virtual DbSet<EmployeePlacement> EmployeePlacement { get; set; }
        public virtual DbSet<EmployeePracticalExperience> EmployeePracticalExperience { get; set; }
        public virtual DbSet<EmployeeQualification> EmployeeQualification { get; set; }
        public virtual DbSet<EmployeeResearch> EmployeeResearch { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalary { get; set; }
        public virtual DbSet<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeTrainingCourse> EmployeeTrainingCourse { get; set; }
        public virtual DbSet<EmployeeVacation> EmployeeVacation { get; set; }
        public virtual DbSet<EmployeeVacationBalance> EmployeeVacationBalance { get; set; }
        public virtual DbSet<EmploymentType> EmploymentType { get; set; }
        public virtual DbSet<EmpStatus> EmpStatus { get; set; }
        public virtual DbSet<FingerprintType> FingerprintType { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Governorate> Governorate { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<HolidayType> HolidayType { get; set; }
        public virtual DbSet<InstructorType> InstructorType { get; set; }
        public virtual DbSet<InstructorTypeHourPrice> InstructorTypeHourPrice { get; set; }
        public virtual DbSet<JobCategory> JobCategory { get; set; }
        public virtual DbSet<JobPersonal> JobPersonal { get; set; }
        public virtual DbSet<JobRequirement> JobRequirement { get; set; }
        public virtual DbSet<JobTask> JobTask { get; set; }
        public virtual DbSet<JobTaskPointer> JobTaskPointer { get; set; }
        public virtual DbSet<JobTerm> JobTerm { get; set; }
        public virtual DbSet<JobType> JobType { get; set; }
        public virtual DbSet<KnowLevel> KnowLevel { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<LateType> LateType { get; set; }
        public virtual DbSet<LogEmployeeVacationBalance> LogEmployeeVacationBalance { get; set; }
        public virtual DbSet<MachineFingerprint> MachineFingerprint { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<MonthDay> MonthDay { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<PersonStatus> PersonStatus { get; set; }
        public virtual DbSet<PlacementStatus> PlacementStatus { get; set; }
        public virtual DbSet<PlacementType> PlacementType { get; set; }
        public virtual DbSet<QualificationType> QualificationType { get; set; }
        public virtual DbSet<RelativeType> RelativeType { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<SalaryBox> SalaryBox { get; set; }
        public virtual DbSet<SalaryBoxType> SalaryBoxType { get; set; }
        public virtual DbSet<SkillType> SkillType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VacationBalanceYear> VacationBalanceYear { get; set; }
        public virtual DbSet<VacationPlace> VacationPlace { get; set; }
        public virtual DbSet<VacationType> VacationType { get; set; }
        public virtual DbSet<EmployeeEmergencyInfo> EmployeeEmergencyInfo { get; set; }
        public virtual DbSet<Sheet1_> Sheet1_ { get; set; }
        public virtual DbSet<AllEmployees> AllEmployees { get; set; }
        public virtual DbSet<NotificationFlag> NotificationFlag { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<ManualFingerprint> ManualFingerprint { get; set; }
        public virtual DbSet<EmployeePersonal> EmployeePersonal { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
    }
}
