//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualFingerprint
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int FingerprintTypeID { get; set; }
        public System.DateTime FingerprintDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> AccreditationStatusID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertEmployeeID { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> AccreditationEmployeeID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteEmployeeID { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
