//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsraaSystem.DataAccess.EntityFrameWork.IsraaHumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int ID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> RecipientID { get; set; }
        public Nullable<int> NotificationFlagID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Href { get; set; }
        public string Recipient_username { get; set; }
        public Nullable<bool> Is_read { get; set; }
        public Nullable<bool> Is_hidden { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual NotificationFlag NotificationFlag { get; set; }
        public virtual EmployeePersonal EmployeePersonal { get; set; }
        public virtual EmployeePersonal EmployeePersonal1 { get; set; }
    }
}
